### ISSUE TITLE
Explorer pagina's API kan al gemaakt worden

### ISSUE THREAD

**Issue by HeinPauwelyn** [WatchFriends/Web#146]
De API request voor de explorer pagina kan al gemaakt worden. Check de url: https://www.watchfriends.me/api/list. In de popular lijst staan er nu nog maar series maar ken uitgebreid worden als je dat wenst. 

Er staan ook andere lijsten zoals _Recommend by friends_, _Today on TV_. Deze twee lijsten worden aangevuld met persoonlijke data.

**Edit:**

- [x] lijsten ophalen
- [x] ~~Series in de lijsten laten afhangen van de gebruikers favoriten~~ ( &rarr; backend)
- [x] Load more knop
- [x] ~~Dingen verbergen indien niet aangemeld~~ &rarr; #155
- [x] ~~Toevoegen aan following~~ &rarr; #155
- [x] ~~Icoon tonen indien je de serie aan het volgen bent.~~ &rarr; #155
- [x] Infinity scroll
- [x] ~~Image not found aanpassen~~ &rarr; @michielzyde

**Comment by HeinPauwelyn** [comment]
Infinity scroll: 

![image](https://cloud.githubusercontent.com/assets/16222780/21727359/61147ff8-d441-11e6-8f85-80437cfa4e6e.png)
