### ISSUE TITLE
Een paar details die opgelost moeten worden

### ISSUE THREAD

**Issue by HeinPauwelyn** [WatchFriends/Web#198]
## Profiel pagina

- [ ] Layout *(zie ook #96 en #188)* 
- [ ] Eigen data afhalen indien `ID` leeg is
- [ ] API request aanpassen

## Navigatie balk

- [ ] Knoppen *Feed* en *Following* verbergen indien niet aangemeld.
- [ ] Ander icoon voor feed. Dacht iets aan een 🔔 icoon.

## Home pagina

- [ ] Carousel werkt niet
- [ ] Register formulier op andere plek zetten. Als ze onder elkaar staan, kan de register formulier er niet volledig op bij te klein computer scherm
- [ ] Foto van de app moet een negatieve `z-index` hebben zodat hij "onder" de footer staan
- [ ] Link voor de app te downloaden. *(Kan maar als https://github.com/WatchFriends/Android/issues/148 in orde is)*

## Aanmelden en registreren

- [ ] Naar home of profiel pagina gaan na aanmelden en registreren
- [ ] Indien aangemeld mag je niet op deze pagina's komen.

## Footer

- [ ] Navigatie in footer + meer info *(zie ook #162)*

**Comment by ExCellRaD** [comment]
> Ander icoon voor feed. Dacht iets aan een 🔔 icoon.

Ook het aantal ongelezen 'events' weergeven hier.

**Comment by ExCellRaD** [comment]
> API request aanpassen

Wat bedoel je hiermee?

**Comment by HeinPauwelyn** [comment]
Ik hab op de backend alles aangepast zodat er nu maar 1 API request hoeft gebeuren. Dit moet wel nog aangepast worden op de frontend.
